site_name: Décisions sur les Déclencheurs Combinés
theme:
  name: material
  logo: ""

  features:
    #- navigation.tabs # décommentez ceci pour afficher la navigation en haut
    - navigation.sections
    - toc.integrate
    #- navigation.footer

nav:
- 'index.md'
- 'options.md'
- 'finished.md'

plugins:
  - search
  - macros

extra:
  kobo_form_id: iusvpk4H
  analytics:
    provider: google
    property: G-YM4PVFJE0F

extra_javascript:
  - javascripts/slide_manager.js
  - javascripts/kobo_loader.js # should no longer be necessary now that there is slide-manager.js

extra_css:
  - stylesheets/styles.css
